
services:
    ngircd:
        image: lscr.io/linuxserver/ngircd:latest
        container_name: ngircd
        ports:
            - 6667:6667
        restart: unless-stopped
    
    marvin:
        build: 
            context: .
            dockerfile: .docker/marvin/Dockerfile
        container_name: MarvinBot
        volumes:
            - ./marvin_config.json:/app/marvin_config.json
            - ./incoming/:/app/incoming/
        depends_on:
            - ngircd

    irssi:
        image: irssi
        container_name: irssi
        environment:
            - TERM=screen-256color
            - COLORTERM=truecolor
        volumes:
            - $HOME/.irssi:/home/user/.irssi:ro
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - ngircd
